---
- name: install and configure frontend 
  hosts: frontend 
  become: true 

  tasks: 
    - name: install nginx 
      apt: 
        name: nginx 

    - name: copy reverse_proxy conf file 
      copy:
        src: reverse_proxy
        dest: /etc/nginx/sites-available/reverse_proxy
      notify: restart nginx

    - name: unlink default page 
      shell: "unlink /etc/nginx/sites-enabled/default"
      ignore_errors: yes 

    - name: create symbolic link 
      file:
        src: /etc/nginx/sites-available/reverse_proxy
        dest: /etc/nginx/sites-enabled/reverse_proxy
        state: link 
      notify: restart nginx 

  handlers: 
    - name: restart nginx 
      service: 
        name: nginx 
        state: restarted 
 
